---
title: "Tutorial writing"
date: 2018-12-27
---
title: Tutorial writing
author: 凛辰过
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  emmmmmm Pay money to my pain is one of my favorite Japanese group. 

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
